# create a namespace for postgres
apiVersion: v1
kind: Namespace
metadata:
  name: postgres

#create a secret
---
apiVersion: v1
kind: Secret 
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= 
  POSTGRES_PASSWORD: a2FuZnUwLW11U2RpcS1zeWhjdXI=

#create a persistent volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# Create PostgreSQL deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              value: postgres

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

#create a service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres

spec:
  selector:
    app: postgres

  ports:
    - port: 5432 
      targetPort: 5432

  type: ClusterIP

#create a persistent volume for backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: postgres

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

#create a cronjob
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: postgres

spec:
  schedule: "0 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup

              image: postgres:16

              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD

              command:
                - /bin/sh
                - -c
                - |
                  pg_dump -h postgres-service -U postgres > /backup/postgres-backup-$(date +\%Y\%m\%d-\%H\%M\%S).sql

              volumeMounts:
                - name: backup-storage
                  mountPath: /backup

          restartPolicy: OnFailure

          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-backup-pvc